spring.application.name=masterdata-inbound

spring.datasource.url=jdbc:postgresql://localhost:5432/masterdata
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

management.endpoints.web.exposure.include=health,info